"""
Supported proxy countries.

Static list — bundled with the SDK so no network call is needed to validate
or autocomplete country codes. The data was generated from
https://api.anakin.io/v1/countries on 2026-04-27.

If Anakin adds new countries, regenerate this file:

    curl -s https://api.anakin.io/v1/countries | python3 scripts/refresh_countries.py

Anakin uses lowercase ISO 3166-1 alpha-2 codes (e.g. "us", "gb", "in").
"""

from __future__ import annotations

from anakin.models import Country

SUPPORTED_COUNTRIES_RAW: list[dict[str, str]] = [
    {"code": 'ad', "name": 'Andorra'},
    {"code": 'ae', "name": 'United Arab Emirates'},
    {"code": 'af', "name": 'Afghanistan'},
    {"code": 'ag', "name": 'Antigua and Barbuda'},
    {"code": 'al', "name": 'Albania'},
    {"code": 'am', "name": 'Armenia'},
    {"code": 'ao', "name": 'Angola'},
    {"code": 'aq', "name": 'Antarctica'},
    {"code": 'ar', "name": 'Argentina'},
    {"code": 'at', "name": 'Austria'},
    {"code": 'au', "name": 'Australia'},
    {"code": 'aw', "name": 'Aruba'},
    {"code": 'ax', "name": 'Aland'},
    {"code": 'az', "name": 'Azerbaijan'},
    {"code": 'ba', "name": 'Bosnia and Herzegovina'},
    {"code": 'bb', "name": 'Barbados'},
    {"code": 'bd', "name": 'Bangladesh'},
    {"code": 'be', "name": 'Belgium'},
    {"code": 'bf', "name": 'Burkina Faso'},
    {"code": 'bg', "name": 'Bulgaria'},
    {"code": 'bh', "name": 'Bahrain'},
    {"code": 'bj', "name": 'Benin'},
    {"code": 'bm', "name": 'Bermuda'},
    {"code": 'bn', "name": 'Brunei'},
    {"code": 'bo', "name": 'Bolivia'},
    {"code": 'bq', "name": 'Bonaire'},
    {"code": 'br', "name": 'Brazil'},
    {"code": 'bs', "name": 'Bahamas'},
    {"code": 'bt', "name": 'Bhutan'},
    {"code": 'bw', "name": 'Botswana'},
    {"code": 'by', "name": 'Belarus'},
    {"code": 'bz', "name": 'Belize'},
    {"code": 'ca', "name": 'Canada'},
    {"code": 'cd', "name": 'Democratic Republic of the Congo'},
    {"code": 'cg', "name": 'Republic of the Congo'},
    {"code": 'ch', "name": 'Switzerland'},
    {"code": 'ci', "name": 'Ivory Coast'},
    {"code": 'ck', "name": 'Cook Islands'},
    {"code": 'cl', "name": 'Chile'},
    {"code": 'cm', "name": 'Cameroon'},
    {"code": 'cn', "name": 'China'},
    {"code": 'co', "name": 'Colombia'},
    {"code": 'cr', "name": 'Costa Rica'},
    {"code": 'cu', "name": 'Cuba'},
    {"code": 'cv', "name": 'Cape Verde'},
    {"code": 'cw', "name": 'Curacao'},
    {"code": 'cy', "name": 'Cyprus'},
    {"code": 'cz', "name": 'Czech Republic'},
    {"code": 'de', "name": 'Germany'},
    {"code": 'dj', "name": 'Djibouti'},
    {"code": 'dk', "name": 'Denmark'},
    {"code": 'do', "name": 'Dominican Republic'},
    {"code": 'dz', "name": 'Algeria'},
    {"code": 'ec', "name": 'Ecuador'},
    {"code": 'ee', "name": 'Estonia'},
    {"code": 'eg', "name": 'Egypt'},
    {"code": 'es', "name": 'Spain'},
    {"code": 'et', "name": 'Ethiopia'},
    {"code": 'fi', "name": 'Finland'},
    {"code": 'fj', "name": 'Fiji'},
    {"code": 'fm', "name": 'Micronesia'},
    {"code": 'fo', "name": 'Faroe Islands'},
    {"code": 'fr', "name": 'France'},
    {"code": 'ga', "name": 'Gabon'},
    {"code": 'gb', "name": 'United Kingdom'},
    {"code": 'gd', "name": 'Grenada'},
    {"code": 'ge', "name": 'Georgia'},
    {"code": 'gf', "name": 'French Guiana'},
    {"code": 'gg', "name": 'Guernsey'},
    {"code": 'gh', "name": 'Ghana'},
    {"code": 'gi', "name": 'Gibraltar'},
    {"code": 'gl', "name": 'Greenland'},
    {"code": 'gn', "name": 'Guinea'},
    {"code": 'gp', "name": 'Guadeloupe'},
    {"code": 'gr', "name": 'Greece'},
    {"code": 'gt', "name": 'Guatemala'},
    {"code": 'gu', "name": 'Guam'},
    {"code": 'gy', "name": 'Guyana'},
    {"code": 'hk', "name": 'Hong Kong'},
    {"code": 'hn', "name": 'Honduras'},
    {"code": 'hr', "name": 'Croatia'},
    {"code": 'ht', "name": 'Haiti'},
    {"code": 'hu', "name": 'Hungary'},
    {"code": 'id', "name": 'Indonesia'},
    {"code": 'ie', "name": 'Ireland'},
    {"code": 'il', "name": 'Israel'},
    {"code": 'im', "name": 'Isle of Man'},
    {"code": 'in', "name": 'India'},
    {"code": 'io', "name": 'British Indian Ocean Territory'},
    {"code": 'iq', "name": 'Iraq'},
    {"code": 'ir', "name": 'Iran'},
    {"code": 'is', "name": 'Iceland'},
    {"code": 'it', "name": 'Italy'},
    {"code": 'je', "name": 'Jersey'},
    {"code": 'jm', "name": 'Jamaica'},
    {"code": 'jo', "name": 'Jordan'},
    {"code": 'jp', "name": 'Japan'},
    {"code": 'ke', "name": 'Kenya'},
    {"code": 'kg', "name": 'Kyrgyzstan'},
    {"code": 'kh', "name": 'Cambodia'},
    {"code": 'kn', "name": 'Saint Kitts and Nevis'},
    {"code": 'kr', "name": 'South Korea'},
    {"code": 'kw', "name": 'Kuwait'},
    {"code": 'ky', "name": 'Cayman Islands'},
    {"code": 'kz', "name": 'Kazakhstan'},
    {"code": 'la', "name": 'Laos'},
    {"code": 'lb', "name": 'Lebanon'},
    {"code": 'lc', "name": 'Saint Lucia'},
    {"code": 'li', "name": 'Liechtenstein'},
    {"code": 'lk', "name": 'Sri Lanka'},
    {"code": 'lr', "name": 'Liberia'},
    {"code": 'ls', "name": 'Lesotho'},
    {"code": 'lt', "name": 'Lithuania'},
    {"code": 'lu', "name": 'Luxembourg'},
    {"code": 'lv', "name": 'Latvia'},
    {"code": 'ly', "name": 'Libya'},
    {"code": 'ma', "name": 'Morocco'},
    {"code": 'mc', "name": 'Monaco'},
    {"code": 'md', "name": 'Moldova'},
    {"code": 'me', "name": 'Montenegro'},
    {"code": 'mf', "name": 'Saint Martin'},
    {"code": 'mg', "name": 'Madagascar'},
    {"code": 'mk', "name": 'North Macedonia'},
    {"code": 'ml', "name": 'Mali'},
    {"code": 'mm', "name": 'Myanmar (Burma)'},
    {"code": 'mn', "name": 'Mongolia'},
    {"code": 'mo', "name": 'Macao'},
    {"code": 'mp', "name": 'Northern Mariana Islands'},
    {"code": 'mq', "name": 'Martinique'},
    {"code": 'mr', "name": 'Mauritania'},
    {"code": 'ms', "name": 'Montserrat'},
    {"code": 'mt', "name": 'Malta'},
    {"code": 'mu', "name": 'Mauritius'},
    {"code": 'mv', "name": 'Maldives'},
    {"code": 'mw', "name": 'Malawi'},
    {"code": 'mx', "name": 'Mexico'},
    {"code": 'my', "name": 'Malaysia'},
    {"code": 'mz', "name": 'Mozambique'},
    {"code": 'na', "name": 'Namibia'},
    {"code": 'nc', "name": 'New Caledonia'},
    {"code": 'ne', "name": 'Niger'},
    {"code": 'ng', "name": 'Nigeria'},
    {"code": 'ni', "name": 'Nicaragua'},
    {"code": 'nl', "name": 'Netherlands'},
    {"code": 'no', "name": 'Norway'},
    {"code": 'np', "name": 'Nepal'},
    {"code": 'nz', "name": 'New Zealand'},
    {"code": 'om', "name": 'Oman'},
    {"code": 'pa', "name": 'Panama'},
    {"code": 'pe', "name": 'Peru'},
    {"code": 'pf', "name": 'French Polynesia'},
    {"code": 'pg', "name": 'Papua New Guinea'},
    {"code": 'ph', "name": 'Philippines'},
    {"code": 'pk', "name": 'Pakistan'},
    {"code": 'pl', "name": 'Poland'},
    {"code": 'pr', "name": 'Puerto Rico'},
    {"code": 'ps', "name": 'Palestine'},
    {"code": 'pt', "name": 'Portugal'},
    {"code": 'py', "name": 'Paraguay'},
    {"code": 'qa', "name": 'Qatar'},
    {"code": 're', "name": 'Reunion'},
    {"code": 'ro', "name": 'Romania'},
    {"code": 'rs', "name": 'Serbia'},
    {"code": 'ru', "name": 'Russia'},
    {"code": 'rw', "name": 'Rwanda'},
    {"code": 'sa', "name": 'Saudi Arabia'},
    {"code": 'sb', "name": 'Solomon Islands'},
    {"code": 'se', "name": 'Sweden'},
    {"code": 'sg', "name": 'Singapore'},
    {"code": 'si', "name": 'Slovenia'},
    {"code": 'sk', "name": 'Slovakia'},
    {"code": 'sl', "name": 'Sierra Leone'},
    {"code": 'sn', "name": 'Senegal'},
    {"code": 'so', "name": 'Somalia'},
    {"code": 'sr', "name": 'Suriname'},
    {"code": 'st', "name": 'Sao Tome and Principe'},
    {"code": 'sv', "name": 'El Salvador'},
    {"code": 'sx', "name": 'Sint Maarten'},
    {"code": 'sy', "name": 'Syria'},
    {"code": 'sz', "name": 'Eswatini'},
    {"code": 'tc', "name": 'Turks and Caicos Islands'},
    {"code": 'tg', "name": 'Togo'},
    {"code": 'th', "name": 'Thailand'},
    {"code": 'tj', "name": 'Tajikistan'},
    {"code": 'tl', "name": 'East Timor'},
    {"code": 'tn', "name": 'Tunisia'},
    {"code": 'to', "name": 'Tonga'},
    {"code": 'tr', "name": 'Turkey'},
    {"code": 'tt', "name": 'Trinidad and Tobago'},
    {"code": 'tw', "name": 'Taiwan'},
    {"code": 'tz', "name": 'Tanzania'},
    {"code": 'ua', "name": 'Ukraine'},
    {"code": 'ug', "name": 'Uganda'},
    {"code": 'us', "name": 'United States'},
    {"code": 'uy', "name": 'Uruguay'},
    {"code": 'uz', "name": 'Uzbekistan'},
    {"code": 'vc', "name": 'Saint Vincent and the Grenadines'},
    {"code": 've', "name": 'Venezuela'},
    {"code": 'vg', "name": 'British Virgin Islands'},
    {"code": 'vi', "name": 'U.S. Virgin Islands'},
    {"code": 'vn', "name": 'Vietnam'},
    {"code": 'vu', "name": 'Vanuatu'},
    {"code": 'xk', "name": 'Kosovo'},
    {"code": 'ye', "name": 'Yemen'},
    {"code": 'za', "name": 'South Africa'},
    {"code": 'zm', "name": 'Zambia'},
    {"code": 'zw', "name": 'Zimbabwe'},
]

SUPPORTED_COUNTRIES: list[Country] = [Country(**c) for c in SUPPORTED_COUNTRIES_RAW]
"""Frozen list of `Country` objects. Order: alphabetical by code."""

SUPPORTED_COUNTRY_CODES: frozenset[str] = frozenset(c.code for c in SUPPORTED_COUNTRIES)
"""Quick membership check for validation: `if "us" in SUPPORTED_COUNTRY_CODES`."""
